In [1]:
def fibonacci_terms (position):
    count=0
    a=0
    b=1
    c=0
    if position==0:
        print("1")
    elif position==1:
        print("3")
    else:
        for c in range (0,position):
            if c==position:
                print(count)
                break   
            c=a+b
            a=b
            b=c
            count +=1
            #print(a)
            
        #print("There are ",count," terms")        
fibonacci_position=int(input("enter a number"))  
fibonacci_terms(fibonacci_position)

enter a number8


In [2]:
def print_even(start,end):
    sum_of_even=0
    while start <= end:
        if start % 2 == 0:
            sum_of_even = sum_of_even + start
        start = start + 1
    print(sum_of_even)
starting_point = int(input("enter the starting point"))
ending_point = int(input("enter the ending point"))
if starting_point < ending_point:
    print_even(starting_point, ending_point)
else:
    print("invalid numbers")

enter the starting point2
enter the ending point5
6


In [2]:
import numpy as np
ary= np.array([1,2,3,4,5])
print(ary)

[1 2 3 4 5]


In [3]:
type(ary)

numpy.ndarray

In [9]:
ary1= np.array(24)
print(ary1)

24


In [5]:
type(ary1)

numpy.ndarray

In [6]:
ary1.dtype

dtype('int32')

In [10]:
ary1.ndim

0

In [11]:
type(ary1)

numpy.ndarray

In [12]:
ary2=np.array([[1,2,3,4,5,6]])

In [13]:
print(ary2)

[[1 2 3 4 5 6]]


In [14]:
type(ary2)

numpy.ndarray

In [15]:
ary2.ndim

2

In [16]:
ary2.dtype

dtype('int32')

In [17]:
ary3=np.array([[[1,2,3],[4,3,2]]])

In [18]:
print(ary3)

[[[1 2 3]
  [4 3 2]]]


In [19]:
ary3.ndim

3

In [20]:
ary3.dtype

dtype('int32')

In [21]:
ary2.shape

(1, 6)

In [97]:
ary33= np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])

In [99]:
print(ary33)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]


In [34]:
print(ary1)

24


In [35]:
arry1=np.array([1,2,3,4])

In [36]:
print(arry1)

[1 2 3 4]


In [50]:
arry1 = np.arange(12)

In [51]:
print(arry1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [53]:
arry2= np.arange(12) .reshape(4,3)

In [54]:
print(arry2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [55]:
arry3= np.ones_like (arry2)

In [56]:
print(arry3)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [60]:
arry4= np.zeros_like(ary1)

In [61]:
print(arry4)

0


In [66]:
arry1[3:5]

array([3, 4])

In [68]:
arry1.max()

11

In [70]:
arry2.max()

11

In [72]:
arry2.mean()

5.5

In [76]:
arry2[[1,2,3]]

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [80]:
arry2[[0,1,2,],[2,1,0]]

array([2, 4, 6, 9])

In [79]:
print(arry2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [100]:
ary33

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [101]:
ary33[[0,1,2],[0,1,2],[3,2,1]]

array([4, 3, 2])

In [102]:
ary33[0,0,2]

3